# Note, this file is only part of the project definition; there is a project
# definition in each file in this directory as well which is combined with
# this.

- project:
    check:
      jobs:
        - zuul-tox-docs
        - tox-py27
        - tox-py38:
            nodeset: ubuntu-focal
        - tox-py39:
            nodeset: ubuntu-focal
        - tox-py310:
            nodeset: ubuntu-jammy
    gate:
      jobs:
        - zuul-tox-docs
        - tox-py27
        - tox-py38:
            nodeset: ubuntu-focal
        - tox-py39:
            nodeset: ubuntu-focal
        - tox-py310:
            nodeset: ubuntu-jammy
    promote:
      jobs:
        - zuul-promote-docs
