- name: List current ipv4 rules
  become: yes
  # Using shell to try and debug why this task when run sometimes returns -13
  shell: iptables-save
  changed_when: false
  failed_when: false
  register: iptables_rules
  tags:
   - skip_ansible_lint

- name: List current ipv6 rules
  become: yes
  # Using shell to try and debug why this task when run sometimes returns -13
  shell: ip6tables-save
  changed_when: false
  failed_when: false
  register: ip6tables_rules
  tags:
   - skip_ansible_lint

- name: Configure persistent iptables rules
  include: "{{ item }}"
  static: no
  with_first_found:
    - "persist/{{ ansible_distribution }}_{{ ansible_distribution_release }}.yaml"
    - "persist/{{ ansible_distribution }}.yaml"
    - "persist/{{ ansible_os_family }}.yaml"
    - "persist/default.yaml"
